# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [87]:
import numpy as np

print(f"Version: {np.__version__}")
np.show_config()

Version: 1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_O

d:\VSCode_Workspaces\MLDM_UNIBS\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [88]:
null_vec = np.zeros(10)
null_vec[4] = 1

print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [89]:
range_mat = np.arange(9).reshape(3, 3)
eye_mat = np.eye(3)
eyed_mat = range_mat - eye_mat * range_mat

print(eyed_mat)

[[0. 1. 2.]
 [3. 0. 5.]
 [6. 7. 0.]]


#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [90]:
ones_mat = np.ones((5,5))
padded_mat = np.pad(ones_mat, ((1,1), (1,1)), 'constant', constant_values=(0))

print(padded_mat)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [91]:
rand_mat = np.random.random((5,5))
norm_mat = (rand_mat - rand_mat.mean()) / rand_mat.std()

print(norm_mat)

[[-1.07791668e+00 -3.09401261e-01 -6.75832647e-01 -1.02400411e+00
  -1.41017280e+00]
 [-3.38394615e-01  1.88270654e+00 -1.19173342e+00 -1.23659250e-01
  -1.39636341e+00]
 [ 1.47380034e-03  1.56519456e+00  1.57213535e+00  1.51026464e+00
   8.02226405e-01]
 [-1.87421017e-01  8.26482263e-01  8.77564141e-01  8.34159352e-01
  -7.76243519e-01]
 [-1.11128711e+00 -5.63413567e-01 -2.57839520e-01 -3.42444106e-01
   9.13919982e-01]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [92]:
dot_mat = np.dot(np.ones((5,3)), np.ones((3,2)))

print(dot_mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [93]:
lin_vec = np.linspace(0, 1, 10 + 1, endpoint=False)[1:]

print(lin_vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [94]:
sorted_vec = np.sort(np.random.uniform(-3, 12, 10))

print(sorted_vec)

[-2.99729583 -2.58412055 -0.70470645  0.40687933  1.02562276  3.17877963
  5.50163429  6.33716137  9.73910578 10.63304487]


#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [95]:
# Create random vector
arg_vec = np.random.random(10)

# Get max and min indices, and corresponding inverse and median
i_max, i_min = np.argmax(arg_vec), np.argmin(arg_vec)
inv_max = -arg_vec.max()
median = np.median(arg_vec)

# Replace within the original vector
arg_vec[i_max] = inv_max
arg_vec[i_min] = median

print(arg_vec)

[ 0.67347433  0.26895993  0.67182002  0.57146719  0.45056409  0.23445839
  0.76845169 -0.8836458   0.85582536  0.62164361]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [96]:
n = 5
p = 10
zero_mat = np.zeros((n,n))

zero_mat.put(np.random.choice(
    zero_mat.size,
    p,
    replace=False
), 1)

print(zero_mat)

[[1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0.]]


#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [97]:
mean_mat = np.random.random((5, 10))
mean_mat -= mean_mat.mean(axis=1, keepdims=True)

print(mean_mat)

[[ 0.42936378 -0.2600182  -0.11842157  0.34789153  0.12122527  0.21698137
  -0.49998939 -0.38527126  0.12165955  0.02657891]
 [-0.38664547 -0.15601392 -0.07956464  0.11443492  0.12734426  0.45155266
   0.01595838  0.02845785 -0.24750456  0.13198054]
 [ 0.07028039 -0.24886639 -0.22901892 -0.09127275 -0.27339897  0.38896086
   0.03102113  0.02575769  0.0357896   0.29074737]
 [ 0.14147862  0.24662605 -0.11047266 -0.44460442 -0.28207322  0.53931917
  -0.20418342 -0.13468769 -0.2908591   0.53945667]
 [ 0.21291471 -0.22349237 -0.02768096 -0.00951616  0.25895021 -0.06232163
   0.04212011 -0.35615007 -0.09052512  0.25570128]]
